"""initial schema

Revision ID: 0a0b1ab87743
Revises:
Create Date: 2026-08-03 17:37:56.937188
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0a0b1ab87743"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("youtube_playlist_name", sa.String(length=255), nullable=True),
        sa.Column("youtube_playlist_id", sa.String(length=128), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("system_managed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
            name=op.f("fk_categories_parent_id_categories"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
    )
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_categories_slug"), ["slug"], unique=True)

    op.create_table(
        "classification_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("rule_config", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classification_rules")),
        sa.UniqueConstraint("name", name=op.f("uq_classification_rules_name")),
    )
    with op.batch_alter_table("classification_rules", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_classification_rules_priority"), ["priority"], unique=False
        )

    op.create_table(
        "sync_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "RUNNING", "COMPLETE", "FAILED", "DRY_RUN", name="syncstatus", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("videos_seen", sa.Integer(), nullable=False),
        sa.Column("videos_created", sa.Integer(), nullable=False),
        sa.Column("videos_changed", sa.Integer(), nullable=False),
        sa.Column("error_information", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_runs")),
    )
    with op.batch_alter_table("sync_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sync_runs_status"), ["status"], unique=False)

    op.create_table(
        "videos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("youtube_video_id", sa.String(length=32), nullable=False),
        sa.Column("canonical_url", sa.String(length=512), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("channel_id", sa.String(length=64), nullable=True),
        sa.Column("channel_name", sa.String(length=255), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("thumbnail_url", sa.String(length=1024), nullable=True),
        sa.Column(
            "availability_status",
            sa.Enum(
                "UNKNOWN",
                "AVAILABLE",
                "UNAVAILABLE",
                "PRIVATE",
                "DELETED",
                name="availabilitystatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("privacy_status", sa.String(length=32), nullable=True),
        sa.Column("liked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_discovered_at", sa.DateTime(), nullable=False),
        sa.Column("last_observed_at", sa.DateTime(), nullable=False),
        sa.Column("metadata_enriched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "transcript_status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "COMPLETE",
                "REVIEW",
                "FAILED",
                "SKIPPED",
                name="processingstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "classification_status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "COMPLETE",
                "REVIEW",
                "FAILED",
                "SKIPPED",
                name="processingstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "playlist_sync_status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "COMPLETE",
                "REVIEW",
                "FAILED",
                "SKIPPED",
                name="processingstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("content_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("raw_metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_videos")),
    )
    with op.batch_alter_table("videos", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_videos_channel_id"), ["channel_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_videos_channel_name"), ["channel_name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_videos_classification_status"), ["classification_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_videos_content_fingerprint"), ["content_fingerprint"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_videos_last_observed_at"), ["last_observed_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_videos_youtube_video_id"), ["youtube_video_id"], unique=True
        )

    op.create_table(
        "browser_actions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("action_key", sa.String(length=512), nullable=False),
        sa.Column("action_type", sa.String(length=64), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("target_playlist_id", sa.String(length=128), nullable=True),
        sa.Column("target_playlist_name", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PLANNED",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "SKIPPED",
                name="actionstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_attempted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_information", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_browser_actions_category_id_categories"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
            name=op.f("fk_browser_actions_video_id_videos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_browser_actions")),
    )
    with op.batch_alter_table("browser_actions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_browser_actions_action_key"), ["action_key"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_browser_actions_category_id"), ["category_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_browser_actions_status"), ["status"], unique=False)
        batch_op.create_index(batch_op.f("ix_browser_actions_video_id"), ["video_id"], unique=False)

    op.create_table(
        "classification_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("raw_response", sa.Text(), nullable=True),
        sa.Column("parsed_result", sa.JSON(), nullable=True),
        sa.Column("token_usage", sa.JSON(), nullable=True),
        sa.Column("estimated_cost", sa.Numeric(precision=12, scale=6), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_information", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
            name=op.f("fk_classification_runs_video_id_videos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classification_runs")),
    )
    with op.batch_alter_table("classification_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_classification_runs_input_hash"), ["input_hash"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_classification_runs_video_id"), ["video_id"], unique=False
        )

    op.create_table(
        "transcripts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("language", sa.String(length=32), nullable=False),
        sa.Column("is_auto_generated", sa.Boolean(), nullable=False),
        sa.Column("transcript_text", sa.Text(), nullable=True),
        sa.Column("segment_json", sa.JSON(), nullable=True),
        sa.Column(
            "retrieval_status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "COMPLETE",
                "REVIEW",
                "FAILED",
                "SKIPPED",
                name="processingstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("retrieval_error", sa.Text(), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("text_hash", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
            name=op.f("fk_transcripts_video_id_videos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transcripts")),
        sa.UniqueConstraint(
            "video_id", "language", "is_auto_generated", name=op.f("uq_transcripts_video_id")
        ),
    )
    with op.batch_alter_table("transcripts", schema=None) as batch_op:
        batch_op.create_index("ix_transcripts_text_hash", ["text_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_transcripts_video_id"), ["video_id"], unique=False)

    op.create_table(
        "video_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("video_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column(
            "assignment_type",
            sa.Enum(
                "RULE",
                "AI",
                "MANUAL",
                "IMPORTED",
                "LEARNED",
                name="assignmenttype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("model_or_rule_identifier", sa.String(length=255), nullable=True),
        sa.Column("approved", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_video_categories_category_id_categories"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["video_id"],
            ["videos.id"],
            name=op.f("fk_video_categories_video_id_videos"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_video_categories")),
        sa.UniqueConstraint(
            "video_id", "category_id", "assignment_type", name=op.f("uq_video_categories_video_id")
        ),
    )
    with op.batch_alter_table("video_categories", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_video_categories_approved"), ["approved"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_video_categories_category_id"), ["category_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_video_categories_video_id"), ["video_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("video_categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_video_categories_video_id"))
        batch_op.drop_index(batch_op.f("ix_video_categories_category_id"))
        batch_op.drop_index(batch_op.f("ix_video_categories_approved"))

    op.drop_table("video_categories")
    with op.batch_alter_table("transcripts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transcripts_video_id"))
        batch_op.drop_index("ix_transcripts_text_hash")

    op.drop_table("transcripts")
    with op.batch_alter_table("classification_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_classification_runs_video_id"))
        batch_op.drop_index(batch_op.f("ix_classification_runs_input_hash"))

    op.drop_table("classification_runs")
    with op.batch_alter_table("browser_actions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_browser_actions_video_id"))
        batch_op.drop_index(batch_op.f("ix_browser_actions_status"))
        batch_op.drop_index(batch_op.f("ix_browser_actions_category_id"))
        batch_op.drop_index(batch_op.f("ix_browser_actions_action_key"))

    op.drop_table("browser_actions")
    with op.batch_alter_table("videos", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_videos_youtube_video_id"))
        batch_op.drop_index(batch_op.f("ix_videos_last_observed_at"))
        batch_op.drop_index(batch_op.f("ix_videos_content_fingerprint"))
        batch_op.drop_index(batch_op.f("ix_videos_classification_status"))
        batch_op.drop_index(batch_op.f("ix_videos_channel_name"))
        batch_op.drop_index(batch_op.f("ix_videos_channel_id"))

    op.drop_table("videos")
    with op.batch_alter_table("sync_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sync_runs_status"))

    op.drop_table("sync_runs")
    with op.batch_alter_table("classification_rules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_classification_rules_priority"))

    op.drop_table("classification_rules")
    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_categories_slug"))

    op.drop_table("categories")
    # ### end Alembic commands ###
